#
# makefile for TINY
# Updated for GNU make with MSVC on Windows and gcc on Unix-like systems
#

ifeq ($(OS),Windows_NT)
SHELL = cmd.exe
MAKESHELL = cmd.exe
VSINSTALL := $(shell "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath)
ifeq ($(strip $(VSINSTALL)),)
$(error Could not locate Visual Studio C++ build tools. Install them or run from a Developer Command Prompt)
endif

EXEEXT = .exe
OBJEXT = .obj
SETUPVC = call "$(VSINSTALL)\VC\Auxiliary\Build\vcvars64.bat" >nul &&
COMPILE.c = $(SETUPVC) cl /nologo /TC /c $< /Fo$@
LINK.tiny = $(SETUPVC) cl /nologo /Fe$@ $(OBJS)
LINK.tm = $(SETUPVC) cl /nologo /TC /Fe$@ TM/tm.c
CLEAN_CMD = -del /Q tiny$(EXEEXT) tm$(EXEEXT) $(OBJS) tm.obj 2>nul
else
EXEEXT =
OBJEXT = .o
CC = gcc
COMPILE.c = $(CC) -x c -c $< -o $@
LINK.tiny = $(CC) -o $@ $(OBJS)
LINK.tm = $(CC) -o $@ TM/tm.c
CLEAN_CMD = rm -f tiny$(EXEEXT) tm$(EXEEXT) $(OBJS) tm.obj
endif

TINY_SRCS = MAIN.C UTIL.C SCAN.C PARSE.C SYMTAB.C ANALYZE.C CODE.C CGEN.C
OBJS = $(addsuffix $(OBJEXT),$(basename $(TINY_SRCS)))

.PHONY: all clean tiny tm

all: tiny$(EXEEXT) tm$(EXEEXT)

tiny$(EXEEXT): $(OBJS)
	$(LINK.tiny)

MAIN$(OBJEXT): MAIN.C GLOBALS.H UTIL.H SCAN.H PARSE.H ANALYZE.H CGEN.H
	$(COMPILE.c)

UTIL$(OBJEXT): UTIL.C UTIL.H GLOBALS.H
	$(COMPILE.c)

SCAN$(OBJEXT): SCAN.C SCAN.H UTIL.H GLOBALS.H
	$(COMPILE.c)

PARSE$(OBJEXT): PARSE.C PARSE.H SCAN.H GLOBALS.H UTIL.H
	$(COMPILE.c)

SYMTAB$(OBJEXT): SYMTAB.C SYMTAB.H
	$(COMPILE.c)

ANALYZE$(OBJEXT): ANALYZE.C GLOBALS.H SYMTAB.H ANALYZE.H
	$(COMPILE.c)

CODE$(OBJEXT): CODE.C CODE.H GLOBALS.H
	$(COMPILE.c)

CGEN$(OBJEXT): CGEN.C GLOBALS.H SYMTAB.H CODE.H CGEN.H
	$(COMPILE.c)

tm$(EXEEXT): TM/tm.c
	$(LINK.tm)

tiny: tiny$(EXEEXT)

tm: tm$(EXEEXT)

clean:
	$(CLEAN_CMD)

